name: frontend
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  flutter_slidable: ^3.1.0
  flutter_native_splash: ^2.4.1

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  http_parser: ^4.0.0
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.3.3
  sqflite: ^2.4.1
  path: ^1.9.0
  intl: ^0.20.1
  flex_color_picker: ^3.6.0
  uuid: ^4.4.0
  connectivity_plus: ^6.1.0
  image_picker: ^1.2.1
  url_launcher: ^6.3.0
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/logo.png
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: assets/icon/logo.png

flutter_native_splash:
  color: "#000000"
  image: assets/icon/logo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/icon/logo.png
    - assets/icon/app_logo.png

  fonts:
    - family: Cera Pro
      fonts:
        - asset: assets/fonts/Cera-Pro-Medium.otf
        - asset: assets/fonts/Cera-Pro-Bold.otf
